version: '3'
services:
  node-service:
    build: ./product
    volumes:
      - ./product:/usr/src/app
    ports:
      - 8081:8081
  nginx:
    image: nginx:1.13
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node-service

  mysql:
      image: mysql:5.7
      volumes:
        - ./data/mysql:/var/lib/mysql
      environment:
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_DATABASE: books
      ports:
        - 3306:3306